enabled: true

messages:
  kick: "§cYou are not in simple whitelist!"
  no_permission: "§cNot enough permissions!"
  invalid_arguments: "§cInvalid arguments!"
  need_player: "§cPlayer's name is needed!"
  already_whitelisted: "§cPlayer is already whitelisted!"
  help: "§5{ §dSimpleWhitelist §5}\n§e:: §7/simplewl add §b<name>\n§e:: §7/simplewl remove §b<name>\n§e:: §7/simplewl enable\n§e:: §7/simplewl disable\n§e:: §7/simplewl reload"

command_messages:
  add: "<name> added to whitelist!"
  remove: "<name> removed from whitelist!"
  list: "In whitelist:\n<list>"
  enable: "Whitelist enabled!"
  disable: "Whitelist disabled!"
  reload: "Reload success!"

whitelist: []